# Generated by Django 5.2.15 on 2026-06-19 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_seed_categories_companions'),
    ]

    operations = [
    ]

DEMO = [
    # ---------------- FUNNY ----------------
    {
        "subject": "DJ Regret", "category": "funny", "companions": ["Friends"],
        "drinks": ["Tequila", "Jagermeister", "Something blue and unlabelled"],
        "meters": [7, 4, 3, 2],
        "story": "I announced to a house party full of strangers that I was the DJ. "
                 "Nobody hired me. I played for three hours. I woke up to a five-star "
                 "review on a Facebook event I was not invited to, and a confirmed "
                 "booking for a child's birthday party next Saturday. I do not own DJ "
                 "equipment. The deposit has cleared.",
    },
    {
        "subject": "The Sock Bandit", "category": "funny", "companions": ["Alone"],
        "drinks": ["Red wine", "More red wine"], "meters": [4, 3, 2, 1],
        "story": "I went to bed alone and woke up wearing one shoe and seven socks, "
                 "none of them mine. I have no memory of acquiring them. I built a small "
                 "shrine to honour them on my windowsill. If they are your socks, I am "
                 "sorry, but they live here now and they are loved.",
    },
    {
        "subject": "Aunty's Worst Nightmare", "category": "funny", "companions": ["Family"],
        "drinks": ["Brandy and Coke"], "meters": [6, 5, 7, 4],
        "story": "At my cousin's kitchen tea I decided to prove the family wrong by "
                 "performing the Macarena at full power. I took out the entire dessert "
                 "table. A trifle did not survive. I am thirty-four years old and my "
                 "mother sent me to sit in the car. I went.",
    },
    {
        "subject": "Captain Verse", "category": "funny", "companions": ["Friends"],
        "drinks": ["Black Label", "Whiskey"], "meters": [7, 4, 4, 3],
        "story": "At a braai I freestyled a full diss track aimed at my cousin Marty "
                 "Eyezlow. By every account it was the best thing I have ever written. I "
                 "remember none of it. Marty filmed the whole thing and is now using it "
                 "as the intro to his next project. I am credited as a feature. I cannot "
                 "recreate a single bar.",
    },
    {
        "subject": "Two-Phone Tony", "category": "funny", "companions": ["Co-workers"],
        "drinks": ["Beer", "Tequila shots", "One mystery shot"], "meters": [6, 5, 6, 5],
        "story": "At the company year-end I emailed the entire staff a meme at 11pm. "
                 "Realising my error, I emailed a heartfelt apology at 11:08pm. The "
                 "apology contained a worse meme. HR has asked me to stop apologising. I "
                 "still have a job. I am choosing to call that a win.",
    },
    {
        "subject": "Modisa After Dark", "category": "funny", "companions": ["Friends"],
        "drinks": ["Gin and tonic", "Black Label"], "meters": [7, 6, 2, 3],
        "story": "I told an entire club I was the artist Modisa. They believed me. They "
                 "pulled me on stage. I then had to actually perform as Modisa with zero "
                 "preparation. Reader, the crowd went up. Security still walked me out "
                 "afterwards, but they were humming the song.",
    },
    {
        "subject": "The Negotiator", "category": "funny", "companions": ["It's complicated"],
        "drinks": ["Vodka cranberry", "Vodka, hold the cranberry"], "meters": [5, 6, 3, 2],
        "story": "I spent twenty minutes negotiating with a vending machine that ate my "
                 "money. I offered it terms. I offered it respect. I lost. I left a "
                 "one-star Google review for the entire building and described the "
                 "machine as, and I quote myself, hostile.",
    },

    # ---------------- WEIRD ----------------
    {
        "subject": "The Phantom of Aisle 9", "category": "weird", "companions": ["Alone"],
        "forgotten": True, "meters": [6, 2, 4, 5],
        "story": "I came to in a 24-hour supermarket while a very patient employee asked "
                 "me to please head home. My trolley contained fourteen limes, a pool "
                 "noodle, and a birthday card addressed to The Moon. I do not know who "
                 "the card was for. I keep the pool noodle by the door now. It feels "
                 "important.",
    },
    {
        "subject": "Frog Whisperer", "category": "weird", "companions": ["Friends"],
        "drinks": ["Cider", "Cider, the sequel"], "meters": [5, 4, 2, 2],
        "story": "I spent an entire evening convinced I could understand a frog at the "
                 "pond. By the end of the night we had, according to my notes, entered "
                 "into a business partnership. I have the napkin contract. The frog's "
                 "signature is just a wet smudge, but a deal is a deal.",
    },
    {
        "subject": "Bheki's Understudy", "category": "weird", "companions": ["Friends"],
        "drinks": ["Black Label", "K20", "Russian bear"], "meters": [6, 5, 2, 3],
        "story": "At my friend Bheki's show, I climbed on stage I climbed on stage and announced I was the emotional "
                 "support hype man. I somehow knew every word of every song. Bheki, who "
                 "is BSM and a professional, did not stop me. I am told I was actually "
                 "good. I have been invited back, which is the part nobody believes.",
    },
    {
        "subject": "The Time Traveler", "category": "weird", "companions": ["Other"],
        "drinks": ["Absinthe", "I stopped reading labels"], "meters": [7, 2, 5, 4],
        "story": "I lost three hours and gained a tattoo of a calculator on my left "
                 "forearm. The calculator is, against all odds, correct in its layout. "
                 "The math I have attempted to do with it is not. I consider this a fair "
                 "trade and I refuse further questions.",
    },
    {
        "subject": "Salt Circle Susan", "category": "weird", "companions": ["Family"],
        "drinks": ["Wedding punch", "More wedding punch"], "meters": [5, 4, 5, 4],
        "story": "At a family wedding I drew a circle of salt around the gift table to "
                 "protect the toaster from demons. The toaster is, I am pleased to "
                 "report, completely fine. I have not been invited to the next wedding. "
                 "The family group chat refers to me only as Susan now. My name is not "
                 "Susan.",
    },
    {
        "subject": "Lord of the Pigeons", "category": "weird", "companions": ["Alone"],
        "drinks": ["Red wine"], "meters": [5, 3, 3, 3],
        "story": "I woke on a park bench with roughly thirty pigeons arranged around me "
                 "like a council. The regulars at the park now greet me by a title I did "
                 "not give myself. The unsettling part is that the pigeons also respond "
                 "to it. I have stopped fighting it.",
    },
    {
        "subject": "The Mannequin Incident", "category": "weird", "companions": ["Co-workers"],
        "forgotten": True, "meters": [6, 2, 4, 3],
        "story": "I have no memory of the night, but I am in possession of a clear "
                 "security photograph of myself shaking hands with a clothing-store "
                 "mannequin to, in my own drunken words, seal the deal. I do not know "
                 "the terms. I do not know the business. I check the news every morning "
                 "in case it went public.",
    },

    # ---------------- HORRIFIC (horror-comedy) ----------------
    {
        "subject": "The Wrong House", "category": "horrific", "companions": ["Friends"],
        "drinks": ["Tequila", "Tequila", "Savana"], "meters": [8, 3, 6, 6],
        "story": "I woke up calmly making breakfast in a kitchen that was not mine, in a "
                 "house that was not mine, for a family that was not mine. They were too "
                 "polite to interrupt. I finished the eggs, left a thank-you note with "
                 "my number, and walked out. They texted me later to say the eggs were "
                 "excellent. We are friends now. I still do not know how I got in.",
    },
    {
        "subject": "3AM Confessional", "category": "horrific", "companions": ["It's complicated"],
        "drinks": ["Red wine", "The rest of the red wine"], "meters": [7, 5, 9, 7],
        "story": "At 3am I sent my ex a two-thousand-word essay, a four-minute voice "
                 "note, and a follow-up message that simply said ignore all of that. "
                 "They did not ignore all of that. Through a series of events too long "
                 "to file here, that same ex is now my landlord. Rent day is the most "
                 "haunted day of my month.",
    },
    {
        "subject": "Tattoo Roulette", "category": "horrific", "companions": ["Friends"],
        "forgotten": True, "meters": [8, 2, 7, 6],
        "story": "I woke with a fresh tattoo of a barcode on my ribs. Out of morbid "
                 "curiosity I scanned it. It is a valid product code for a brand of "
                 "canned beans that was discontinued in 2009. I carry the beans of a "
                 "dead brand on my body forever. I have made my peace. Mostly.",
    },
    {
        "subject": "The Group Chat Massacre", "category": "horrific", "companions": ["Co-workers"],
        "drinks": ["Tequila shots", "Beer", "A shot someone called The Decision"],
        "meters": [9, 5, 8, 7],
        "story": "I added the entire office, including senior management, to a group "
                 "chat with a name I cannot repeat in an official report. I then left "
                 "the chat, which meant I alone could not see it, but everyone else "
                 "could. I could not remove it. I could not undo it. I lay on the floor "
                 "and watched the notification count climb for six hours like a man "
                 "watching a wave he could not outrun.",
    },
    {
        "subject": "Best Man Down", "category": "horrific", "companions": ["Family"],
        "drinks": ["Champagne", "Whiskey", "More champagne to balance the whiskey"],
        "meters": [8, 6, 8, 6],
        "story": "My best man speech opened beautifully and then, with the confidence "
                 "only a bottle of champagne can provide, revealed a secret that three "
                 "families did not know. The marriage survived. It is, in fact, "
                 "thriving. My friendship with the groom has entered a kind of witness "
                 "protection. We do not speak of the speech. We do not speak much at all.",
    },

    # ---------------- HORRIFIC (grim) ----------------
    {
        "subject": "The Long Walk Home", "category": "horrific", "companions": ["Alone"],
        "drinks": ["Vodka", "I lost count after that"], "meters": [9, 2, 9, 9],
        "story": "I decided, alone and far past sensible, to walk home through a part of "
                 "the city I did not know at three in the morning. I blacked out. I came "
                 "to two suburbs over with no phone and one shoe. A stranger, I later "
                 "pieced together, had quietly walked beside me until I was safe at a "
                 "petrol station and waited there until a taxi came. I never learned "
                 "their name. I tell someone where I am every single night now. That "
                 "part is not a joke.",
    },
    {
        "subject": "Last Round", "category": "horrific", "companions": ["Friends"],
        "forgotten": True, "meters": [10, 1, 10, 10],
        "story": "I do not remember the fall. I remember waking up in a hospital bed "
                 "with a drip in my arm and a nurse who had clearly already decided what "
                 "she thought of me. There is a scar now that does not let me forget. I "
                 "have not touched the hard stuff since. I am filing this not as a brag "
                 "but as a warning from the other side of a night that very nearly did "
                 "not have a morning. Laugh at the rest of these. Learn from this one.",
    },
]


def seed(apps, schema_editor):
    Category = apps.get_model("stories", "Category")
    Companion = apps.get_model("stories", "Companion")
    Story = apps.get_model("stories", "Story")
    Drink = apps.get_model("stories", "Drink")

    cats = {c.slug: c for c in Category.objects.all()}
    comps = {c.label: c for c in Companion.objects.all()}

    for d in DEMO:
        story = Story.objects.create(
            subject=d["subject"],
            category=cats[d["category"]],
            drinks_forgotten=d.get("forgotten", False),
            story_text=d["story"],
            chaos_level=d["meters"][0],
            memory_of_event=d["meters"][1],
            regret_level=d["meters"][2],
            lesson_learned=d["meters"][3],
            status="approved",
        )
        story.companions.set([comps[label] for label in d["companions"]])
        for name in d.get("drinks", []):
            Drink.objects.create(story=story, name=name)


def unseed(apps, schema_editor):
    Story = apps.get_model("stories", "Story")
    Story.objects.filter(subject__in=[d["subject"] for d in DEMO]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0002_seed_categories_companions"),
    ]
    operations = [
        migrations.RunPython(seed, unseed),
    ]